# Generated by Django 4.2 on 2023-04-14 05:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crimsonboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': '5. Students'},
        ),
        migrations.RenameField(
            model_name='student',
            old_name='address',
            new_name='interested_categories',
        ),
        migrations.RemoveField(
            model_name='student',
            name='mobile_number',
        ),
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
