# Generated by Django 4.2 on 2023-04-18 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimsonboard', '0005_studentcourseenrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.CharField(default='student_dummy', max_length=100, null=True),
        ),
    ]
