# Generated by Django 4.2 on 2023-04-20 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crimsonboard', '0007_instructor_bio_instructor_login_via_otp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='login_via_otp',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='otp_digit',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='verify_status',
        ),
        migrations.RemoveField(
            model_name='student',
            name='login_via_otp',
        ),
        migrations.RemoveField(
            model_name='student',
            name='otp_digit',
        ),
        migrations.RemoveField(
            model_name='student',
            name='verify_status',
        ),
    ]
