# Generated by Django 4.2 on 2023-04-20 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimsonboard', '0008_remove_instructor_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='bio',
            field=models.TextField(default='Bio', null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='profile_img',
            field=models.ImageField(null=True, upload_to='instructor_profile_imgs/'),
        ),
    ]
