# Generated by Django 4.2 on 2023-04-21 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crimsonboard', '0012_alter_assignmentresponse_response_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignmentresponse',
            old_name='response_file',
            new_name='submission_file',
        ),
    ]
