# Generated by Django 4.2 on 2023-04-22 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crimsonboard', '0013_rename_response_file_assignmentresponse_submission_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentresponse',
            name='reponse_text',
            field=models.TextField(default='Submission Done', null=True),
        ),
        migrations.AlterField(
            model_name='assignments',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_assignments', to='crimsonboard.course'),
        ),
    ]
