# Generated by Django 4.2 on 2023-04-23 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crimsonboard', '0016_alter_assignments_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentresponse',
            name='assignment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='assignmentSubmissions', to='crimsonboard.assignments'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignmentresponse',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crimsonboard.course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignmentresponse',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crimsonboard.student'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignmentresponse',
            name='submission_file',
            field=models.FileField(null=True, upload_to='responses/'),
        ),
    ]
